#!/bin/bash
echo "Monitoramento de subidas e alteracoes no ambiente, qualquer subida somente com CRQ e formalizada ao PCP"
echo "--------------------"
#kubectl get rs -n production | awk '{print $1} {printf "%s ",$5}' | grep ^[1-9][1-9]m
echo "check RS in last minutes:"
#kubectl get rs -n production | awk '{print $1} {printf "%s ",$5}' | grep ^[1-9][1-9]m
D=$(kubectl get rs -n producao | awk '{print $1} {printf "%s ",$5}' | grep ^[0-9]m)
A=$(kubectl get rs -n producao | awk '{print $1} {printf "%s ",$5}' | grep ^[0-9][0-9]m)
C=$(kubectl get rs -n producao | awk '{print $1} {printf "%s ",$5}' | grep ^[0-9][0-9][0-9]m)
echo "$D"
echo "$A"
echo "$C"
echo ""
B=$(kubectl get rs -n producao | awk '{print $1} {printf "%s ",$5}' | grep ^[0-9][0-9]h)
echo "check RS in last hours:"
echo "$B"
echo ""

echo "Check Deployments"
x=$(kubectl get deploy -n producao -o wide  | awk '{print $1} {printf "%s ",$5}' | grep ^[0-9]m)
exit 0
